services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    restart: always
    networks:
      - devsecops_network
  jenkins:
    build: ./jenkins/
    restart: always
    user: root
    expose:
      - "8080"
      - "50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - devsecops_network
  db:
    image: postgres:12.7-alpine
    restart: always
    container_name: faraday_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=faraday
    expose:
      - '5432'
    volumes:
      - "db:/var/lib/postgresql/data"
    networks:
      - devsecops_network
  redis:
    image: 'redis:6.2-alpine'
    container_name: faraday_redis
    expose:
      - '6379'
    networks:
      - devsecops_network
  faraday:
    image: faradaysec/faraday:5.0.0
    restart: always
    container_name: faraday_app
    entrypoint: "/entrypoint.sh"
    volumes:
      - "faraday:/home/faraday/.faraday"
    environment:
      - PGSQL_USER=postgres
      - PGSQL_PASSWD=postgres
      - PGSQL_HOST=db
      - PGSQL_DBNAME=faraday
      - REDIS_SERVER=redis
    depends_on:
      - db
      - redis
    expose:
      - "5985"
    networks:
      - devsecops_network

volumes:
  jenkins_home:
  faraday:
  db:

networks:
  devsecops_network:
