jenkins:
  systemMessage: "Jenkins сконфигурирован автоматически при помощи JCasC."

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

        - id: "developer"
          password: "developer"

        - id: "viewer"
          password: "viewer"

  authorizationStrategy:
    projectMatrix:
      entries:
        - user:
            name: admin
            permissions:
              - Overall/Administer
        - user:
            name: developer
            permissions:
              - Overall/Read
              - Job/Build
        - user:
            name: viewer
            permissions:
              - Overall/Read

tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"
  maven:
    installations:
      - name: maven3
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.8.4"

jobs:
  - script: >
      pipelineJob('Template DevSecOps pipeline') {
        parameters {
          stringParam('REPO_URL', 'https://github.com/kaakaww/vuln_django_play', 'URL репозитория для клонирования')
          stringParam('BRANCH_NAME', 'main', 'Ветка для клонирования')
        }
        definition {
          cps {
            script(''' 
                pipeline {
                    agent any
                    stages {
                        stage('Checkout') {
                            steps {
                                sh 'git clone https://github.com/jinghao1/DockerVulspace'
                            }
                        }
                        stage('SAST (Bandit)') {
                            agent {
                                docker {
                                    image 'python:3.10'
                                    reuseNode true
                                }
                            }
                            steps {
                                echo 'Preparing environment...'
                                sh 'pip install bandit'
                                sh 'ls -la'
      
                                echo 'Runnig SAST...'
                                sh 'python3 -m bandit -r . -f xml -o bandit_sast.xml || true'
      
                                archiveArtifacts artifacts: 'bandit_sast.xml', allowEmptyArchive: true, fingerprint: true
                            }
                        }
                    }
                }
            ''')
          }
        }
      }
